NAME=LLama_8B_4K_pp_run16_plan_4_new_DP_pp
NNODES=2
NPROC_PER_NODE=8
PLAN_NGPUS=8
RUNTIME_NGPUS=16
DATASIZE=4K
MODEL_ID=/data/haiqwa/zevin_nfs/andy/Auto-Parallelization/nnscaler_group1/llama-model-config/Meta-Llama-3.1-8B
DATASET_PATH=/data/haiqwa/zevin_nfs/dataset/bookcorpus_llama3_4K
CODE=/data/haiqwa/zevin_nfs/andy/Auto-Parallelization/nnscaler_group1/nnscaler-new/examples/llama/train.py
PIPLINE=True