NAME=LLAMA_8B_4K_pp_run8_plan
NNODES=1
NPROC_PER_NODE=8
PLAN_NGPUS=8
RUNTIME_NGPUS=8
DATASIZE=4K
MODEL_ID=/data/haiqwa/zevin_nfs/code/verl/examples/resources/Llama-3-8B
DATASET_PATH=/data/haiqwa/zevin_nfs/andy/Auto-Parallelization/nnscaler_group1/datasets/bookcorpus_4K_LLAMA
CODE=/data/haiqwa/zevin_nfs/andy/Auto-Parallelization/nnscaler_group1/nnscaler-h3c/examples/llama/train.py
PIPLINE=True
