NAME=llama3_8b_pp_plan8_run8
NNODES=1
NPROC_PER_NODE=8
PLAN_NGPUS=8
RUNTIME_NGPUS=8
MODEL_ID=/data/haiqwa/gpt/jcz/Meta-Llama-3.1-8B-Instruct
DATASET_PATH=/data/haiqwa/zevin_nfs/dataset/bookcorpus_llama3_4K
CODE=/data/haiqwa/zevin_nfs/andy/Auto-Parallelization/nnscaler_group1/nnscaler-0.4/examples/llama3_8B_128K/train.py
USE_ZERO=1
PAS_PRIORITY=time